# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 02:26
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User
from dartcms.apps.modules.models import ModuleGroup, Module

MODULE_GROUPS = [
    {
        'sort': 1,
        'description': '',
        'fa': 'fa-flag',
        'name_en': 'Administration',
        'slug': 'admin',
        'name': u'Администрирование',
        'modules': [
            {
                'sort': 1,
                'is_enabled': True,
                'name': u'Пользователи CMS',
                'name_en': 'CMS Users',
                'slug': 'cms-users',
                'description': ''
            }
        ]
    },
    {
        'sort': 2,
        'description': '',
        'fa': 'fa-file',
        'name_en': 'Content',
        'slug': 'content',
        'name': u'Контент'
    },
    {
        'sort': 3,
        'description': '',
        'fa': 'fa-cog',
        'name_en': 'Services',
        'slug': 'service',
        'name': u'Сервисы'
    }
]


def insert_modules(apps, schema):
    superuser = User.objects.filter(is_superuser=True).first()

    if not superuser:
        raise Exception('You should create at least one superuser first.')

    for group in MODULE_GROUPS:
        group_modules = group.pop('modules', [])
        group = ModuleGroup.objects.create(**group)
        for module in group_modules:
            module['group'] = group
            obj = Module.objects.create(**module)
            superuser.module_set.add(obj)


def delete_modules(apps, schema):
    for group in MODULE_GROUPS:
        ModuleGroup.objects.get(slug=group['slug']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_modules, delete_modules)
    ]
